---
- name: Build and push Docker image to Docker Hub
  hosts: localhost
  tasks:
    - name: Stop previous container if running
      become: yes
      command: docker stop my-angular-app-container
      ignore_errors: yes

    - name: Remove previous container if exists
      become: yes
      command: docker rm my-angular-app-container
      ignore_errors: yes

    - name: Build Docker image
      become: yes
      command: docker build -t my-angular-app-image .

      - name: Run Docker container from Docker Hub image
      become: yes
      command: docker run -d --name my-angular-app-container -p 80:80 rafikzoubli/my-angular-app-image


    - name: Tag Docker image for Docker Hub
      become: yes
      command: docker tag my-angular-app-image rafikzoubli/my-angular-app-image

    - name: Docker login to Docker Hub
      become: yes
      command: docker login -u rafikzoubli -p dckr_pat_f9XpBNs_8cbRoKNSLCvnSRdWvXw

    - name: Push Docker image to Docker Hub
      become: yes
      command: docker push rafikzoubli/my-angular-app-image
