---
- name: Build and run Docker image
  hosts: localhost
  tasks:
    - name: Build Docker image
      become: yes
      command: docker build -t my-angular-app-image .

    - name: Run Docker container
      become: yes
      command: docker run -d -p 80:80 my-angular-app-image
